project:
  type: website

website:
  title: "Tá, mas e a economia?"
  favicon: imagens/logo.png
  navbar:
    logo: imagens/logo.png
    background: "#04147c"
    foreground: "white"
    right:
      - text: "Início"
        href: index.qmd
      - text: "Newsletter"
        file: Newsletter/indexNe.qmd
      - text: "Índices"
        file: indices/index.qmd
      - text: "Quem somos?"
        href: sobre.qmd
      - text: "Receba no email"
        href: email.qmd
      - icon: instagram
        href: https://www.instagram.com/tamaseaeconomia
        aria-label: Instagram

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    lang: pt-BR
    date-format: "DD/MM/YYYY"
    labels:
      author: Autor
      published: Publicado em

editor: visual

