project:
  type: website

website:
  title: "Portal Economia"
  navbar:
    left:
      - text: "Início"
        href: index.qmd
      - text: "Newsletter"
        href: newsletter.qmd
      - text: "Índices"
        href: indices.qmd
      - text: "Quem somos?"
        href: sobre.qmd
      - text: "Receba no email"
        href: email.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

